<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20851" started-at="2018-12-21T08:43:29Z" finished-at="2018-12-21T08:43:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20851" started-at="2018-12-21T08:43:29Z" finished-at="2018-12-21T08:43:50Z">
      <class name="com.training.sanity.tests.searchcourse_Test">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.searchcourse_Test@42d80b78]" name="setUpBeforeClass" is-config="true" duration-ms="12625" started-at="2018-12-21T08:43:29Z" finished-at="2018-12-21T08:43:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="validAddCourse()[pri:1, instance:com.training.sanity.tests.searchcourse_Test@42d80b78]" name="validAddCourse" duration-ms="6074" started-at="2018-12-21T08:43:42Z" finished-at="2018-12-21T08:43:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validAddCourse -->
        <test-method status="FAIL" signature="validcataloguesearch()[pri:2, instance:com.training.sanity.tests.searchcourse_Test@42d80b78]" name="validcataloguesearch" duration-ms="3" started-at="2018-12-21T08:43:48Z" finished-at="2018-12-21T08:43:48Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.training.sanity.tests.searchcourse_Test.validcataloguesearch(searchcourse_Test.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validcataloguesearch -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.searchcourse_Test@42d80b78]" name="tearDown" is-config="true" duration-ms="2017" started-at="2018-12-21T08:43:48Z" finished-at="2018-12-21T08:43:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.searchcourse_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
